### LISTAR TODOS OS USUARIOS
GET  http://localhost:3000/usuarios

### LISTAR USUARIOS POR ID
GET http://localhost:3000/usuarios/1

### CADASTRAR NOVO USUARIO
POST  http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Charles Tompson"
};

### ATUALIZAR USUARIO
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome": "Thomas Jefferson"
}